name = "expense-ai-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "YOUR_KV_ID"

[[r2_buckets]]
binding = "R2_RECEIPTS"
bucket_name = "expense-ai-receipts"
