name = "notaku-api-gateway"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
BACKEND_FASTAPI_URL = "http://172.16.1.7:8000"

[[routes]]
pattern = "backend.notaku.cloud/*"
zone_name = "notaku.cloud"

[build]
command = "npm install && npm run build"

[observability]
enabled = true
