name = "notaku-frontend"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "notaku-frontend"

[env.preview]
name = "notaku-frontend-preview"
